version: '4'

services:
  app:
    build: .
    container_name: flask-login
    command: sh -c "gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"
    restart: always
    volumes:
      - .:/app
    expose:
      - '8000'
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
